.TH MSI 1 2023/07/23
.SH NAME
miniSEED Inspector

.SH SYNOPSIS
.nf
msi [options] file1 [file2 file3 ...]

.fi
.SH DESCRIPTION
\fBmsi\fP is a general purpose miniSEED parser.  In addition to
parsing and displaying the contents of miniSEED records, \fBmsi\fP
will derive continuous trace information for miniSEED data.

By default, \fBmsi\fP will output a single line of information to
summarize each record parsed.  More verbose or different output can be
specified via the numerous options.

If '-' is specified standard input will be read.  Multiple input files
will be processed in the order specified.

Files on the command line prefixed with a '@' character are input list
files and are expected to contain a simple list of input files, see
\fBINPUT LIST FILE\fR for more details.

When a input file is full SEED including both SEED headers and data
records all of the headers will be skipped and completely unprocessed
unless the \fB-y\fP option has been specified.

.SH OPTIONS

.IP "-V         "
Print program version and exit.

.IP "-h         "
Print program usage and exit.

.IP "-v         "
Be more verbose.  This flag can be used multiple times ("-v -v" or
"-vv") for more verbosity.

.IP "-H \fIHeader\fP"
Add custom header to URL-based reads.  Only available when compiled
with URL support.

.IP "-u \fIuser:pass\fP"
Set \fIuser\fP and \fIpass\fP credentials for URL-based reads.  Only
available when compiled with URL support.

.IP "-ts \fItime\fP"
Limit processing to miniSEED records that contain or start after
\fItime\fP.  The format of the \fItime\fP arguement
is: 'YYYY[-MM-DDThh:mm:ss.ffff], or 'YYYY[,DDD,HH,MM,SS,FFFFFF]',
or Unix/POSIX epoch seconds.

.IP "-te \fItime\fP"
Limit processing to miniSEED records that contain or end before
\fItime\fP.  The format of the \fItime\fP arguement
is: 'YYYY[-MM-DDThh:mm:ss.ffff], or 'YYYY[,DDD,HH,MM,SS,FFFFFF]',
or Unix/POSIX epoch seconds.

.IP "-m \fImatch\fP"
Limit processing to miniSEED records that contain the \fImatch\fP
pattern, which is applied to the Source Identifier for each record,
often following this pattern:
'FDSN:<network>_<station>_<location>_<band>_<source>_<subsource>'

.IP "-r \fIreject\fP"
Limit processing to miniSEED records that do _not_ contain the
\fIreject\fP pattern, which is applied to the the Source Identifier
for each record, often following this pattern:
'FDSN:<network>_<station>_<location>_<band>_<source>_<subsource>'

.IP "-n \fIcount\fP"
Only process \fIcount\fP input records.

.IP "-snd       "
Skip non-miniSEED records.  By default the program will stop when
it encounters data that cannot be identified as a miniSEED record.
This option can be useful with full SEED volumes or files with bad
data.

.IP "-p         "
Print details of each record header.  This flag can be used multiple
times ("-p -p" or "-pp") for more verbosity.  Specifying two flags
will result in all header details being printed.

.IP "-O         "
Include the offset into the file in bytes when printing header
details.

.IP "-L         "
Include data latency when printing header details.  The latency is
calculated as the difference between the time of the last sample and
the current time from the host computer.

.IP "-s         "
Print a basic summary including the number of records and the number
of samples they included after processing all input records.

.IP "-d          "
Decompress/unpack data in input records and print the first 6 sample
values from each record.

.IP "-D          "
Decompress/unpack data in input records and print all the sample
values.

.IP "-t         "
Print a sorted trace list after processing all input records.

.IP "-T         "
Print a sorted trace list after processing all input records and
suppress record-by-record output, i.e. trace list only.

.IP "-tg        "
Include gap estimates when approriate in trace listings and
suppress record-by-record output, i.e. trace list only.

.IP "-tt \fIsecs\fP"
Specify a time tolerance for constructing continous trace
segments. The tolerance is specified in seconds.  The default
tolerance is 1/2 of the sample period.

.IP "-rt \fIdiff\fP"
Specify a sample rate tolerance for constructing continous trace
segments. The tolerance is specified as the difference between two
sampling rates.  The default tolerance is tested as: (abs(1-sr1/sr2) <
0.0001).

.IP "-g         "
Print a sorted gap/overlap list after processing all input records.

.IP "-G         "
Print a sorted gap/overlap list after processing all input records and
suppress record-by-record output, i.e. gap list only.

.IP "-gmin \fIsec\fP"
Only include gaps in the gap list larger or equal to \fIsec\fP number
of seconds.

.IP "-gmax \fIsec\fP"
Only include gaps in the gap list smaller or equal to \fIsec\fP number
of seconds.

.IP "-S         "
Print a sorted SYNC format trace list after processing all input
records and suppress record-by-record output.

.IP "-P         "
Additionally group input data by publication.  Note: for miniSEED
version 2 records, SEED data qualitiy values are translated to
publication versions. By default data are grouped by network, station,
location, channel and adjacent time windows, this option adds
publication version to the grouping parameters.

.IP "-tf \fIformat\fP"
Specify the time stamp format for trace and gap/overlap lists.  The
\fIformat\fP can be one of the following (default = 0):
.nf
  0 = SEED day-of-year time, e.g. "2005,068,00:00:01.000000"
  1 = ISO year-month-day time, e.g. "2005-03-09T00:00:01.000000"
  2 = Epoch seconds, e.g. "1110326401.000000"
.fi

.IP "-b \fIbinfile\fP"
Decompress/unpack data in input records and write the binary samples
to \fIbinfile\fP.

.IP "-o \fIoutfile\fP"
Write all processed miniSEED records to \fIoutfile\fP.

.SH "INPUT FILES"

An input file name may be followed by an \fB@\fP charater followed by
a byte range in the pattern \fBSTART[-END]\fP, where the END offset is
optional.  As an example an input file specified as
\fBANMO.mseed@8192\fP would result in the file \fBANMO.mseed\fP being
read starting at byte 8192.  An optional end offset can be specified,
e.g. \fBANMO.mseed@8192-12288\fP would start reading at offset 8192
and stop after offset 12288.

.SH "INPUT LIST FILE"
A list file can be used to specify input files, one file per line.
The initial '@' character indicating a list file is not considered
part of the file name.  As an example, if the following command line
option was used:

.nf
\fB@files.list\fP
.fi

The 'files.list' file might look like this:

.nf
data/day1.mseed
data/day2.mseed
data/day3.mseed
.fi

.SH LEAP SECOND LIST FILE
NOTE: A list of leap seconds is included in the program and no external
list should be needed unless a leap second is added after year 2023.

If the environment variable LIBMSEED_LEAPSECOND_FILE is set it is
expected to indicate a file containing a list of leap seconds as
published by NIST and IETF, usually available here:
https://www.ietf.org/timezones/data/leap-seconds.list

If present, the leap seconds listed in this file will be used to
adjust the time coverage for records that contain a leap second.
Also, leap second indicators in the miniSEED headers will be ignored.

.SH AUTHOR
.nf
Chad Trabant
EarthScope Data Services
.fi
